version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080" # this is the port for the jenkins web interface
      - "50000:50000" # this is the port for the jenkins slave agent