apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: 2-k8s/k8s
    repoURL: 'https://github.com/DevOps-RT5-Labs/Labs'
    targetRevision: dev
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true